export const flagMap: Record<string, string> = {
    'Argentina': 'ar',
    'France': 'fr',
    'Brazil': 'br',
    'England': 'gb-eng',
    'Portugal': 'pt',
    'Netherlands': 'nl',
    'Spain': 'es',
    'Germany': 'de',
    'Italy': 'it',
    'Belgium': 'be',
    'Croatia': 'hr',
    'Uruguay': 'uy',
    'Morocco': 'ma',
    'Switzerland': 'ch',
    'USA': 'us',
    'Mexico': 'mx',
    'Canada': 'ca',
    'Japan': 'jp',
    'South Korea': 'kr',
    'Senegal': 'sn',
    'Poland': 'pl',
    'Australia': 'au',
    'Ecuador': 'ec',
    'Saudi Arabia': 'sa',
    'Iran': 'ir',
    'Costa Rica': 'cr',
    'Tunisia': 'tn',
    'Cameroon': 'cm',
    'Ghana': 'gh',
    'Serbia': 'rs',
    'Wales': 'gb-wls',
    'Denmark': 'dk',
    'Sweden': 'se',
    'Colombia': 'co',
    'Chile': 'cl',
    'Peru': 'pe',
    'Nigeria': 'ng',
    'Egypt': 'eg',
    'Algeria': 'dz',
    'Ivory Coast': 'ci',
    'South Africa': 'za',
    'Qatar': 'qa',
    'Turkey': 'tr',
    'Austria': 'at',
    'Hungary': 'hu',
    'Scotland': 'gb-sct',
    'Czech Republic': 'cz',
    'Ukraine': 'ua',
    'Romania': 'ro',
    'Slovakia': 'sk',
    'Slovenia': 'si',
    'Georgia': 'ge',
    'Albania': 'al',
    'Paraguay': 'py',
    'Norway': 'no',
    'Congo DR': 'cd',
    'Bosnia & Herzegovina': 'ba',
    'Cape Verde Islands': 'cv',
};

export function getFlagUrl(teamName: string): string | null {
    const name = teamName.trim();
    if (flagMap[name]) {
        return `https://flagcdn.com/w40/${flagMap[name]}.png`;
    }
    return null;
}
