export const flagMap: Record<string, string> = {
    'Argentina': '🇦🇷',
    'France': '🇫🇷',
    'Brazil': '🇧🇷',
    'England': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    'Portugal': '🇵🇹',
    'Netherlands': '🇳🇱',
    'Spain': '🇪🇸',
    'Germany': '🇩🇪',
    'Italy': '🇮🇹',
    'Belgium': '🇧🇪',
    'Croatia': '🇭🇷',
    'Uruguay': '🇺🇾',
    'Morocco': '🇲🇦',
    'Switzerland': '🇨🇭',
    'USA': '🇺🇸',
    'Mexico': '🇲🇽',
    'Canada': '🇨🇦',
    'Japan': '🇯🇵',
    'South Korea': '🇰🇷',
    'Senegal': '🇸🇳',
    'Poland': '🇵🇱',
    'Australia': '🇦🇺',
    'Ecuador': '🇪🇨',
    'Saudi Arabia': '🇸🇦',
    'Iran': '🇮🇷',
    'Costa Rica': '🇨🇷',
    'Tunisia': '🇹🇳',
    'Cameroon': '🇨🇲',
    'Ghana': '🇬🇭',
    'Serbia': '🇷🇸',
    'Wales': '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
    'Denmark': '🇩🇰',
    'Sweden': '🇸🇪',
    'Colombia': '🇨🇴',
    'Chile': '🇨🇱',
    'Peru': '🇵🇪',
    'Nigeria': '🇳🇬',
    'Egypt': '🇪🇬',
    'Algeria': '🇩🇿',
    'Ivory Coast': '🇨🇮',
    'South Africa': '🇿🇦',
    'Qatar': '🇶🇦',
    'Turkey': '🇹🇷',
    'Austria': '🇦🇹',
    'Hungary': '🇭🇺',
    'Scotland': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    'Czech Republic': '🇨🇿',
    'Ukraine': '🇺🇦',
    'Romania': '🇷🇴',
    'Slovakia': '🇸🇰',
    'Slovenia': '🇸🇮',
    'Georgia': '🇬🇪',
    'Albania': '🇦🇱',
};

export function getFlagEmoji(teamName: string): string {
    const name = teamName.trim();
    if (flagMap[name]) {
        return flagMap[name];
    }
    // Return empty or a generic icon if not found
    return '';
}
